<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title><?php echo $pageTitle ;?></title>
        <link href="<?php echo $style;?>" media="screen, projection" rel="stylesheet" type="text/css" />
        <script src="<?php echo $script;?>"></script>
    </head>
    <body>
        <header>
            <h1>UTM Framework</h1>
        </header>
        <div id="main">
            <?php echo $main ;?>    
        </div>        
        <footer>
            <a href="https://www.dizagn.com">www.dizagn.com</a>
            <div id="footer-extra">
                <a href="mailto:utm-project@dizagn.com"><img src="img/logo-contactus.png"></a>                        
                <a href="https://github.com/Dizagn/utm" target="_blank"><img src="img/logo-github.png"></a>
                <a href="https://twitter.com/dizagn" target="_blank"><img src="img/logo-twitter.png"></a>
            </div>  
        </footer>
    </body>
</html>
