<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title><?php echo $pageTitle ;?></title>
        <link href="<?php echo $style;?>" media="screen, projection" rel="stylesheet" type="text/css" />
        <script src="<?php echo $script;?>"></script>
    </head>
    <body>
        <header>
            <h1>Framework UTM</h1>
        </header>
        <div id="main">
            <?php echo $main ;?>    
        </div>        
        <footer>
            <a href="https://www.dizagn.com">www.dizagn.com</a>
        </footer>
    </body>
</html>
