<h2>Well done ! Your first UTM web page with using a layout !! </h2>
<div>
    <h3>Get started</h3>
    If you see this page, then you have surely well installed this framework, webserver and php engine.
    To begin your project you can take a look at this files first to understand how it works :
    <pre>
    - application/component/layout/basic.phtml -> A html5 layout template
    - application/component/layout/basicView.php -> The layout view who load the basic template
    - application/component/index/index.phtml -> The default template page "index"
    - application/component/index/indexView.php -> The default view using the basic layout output</pre>
    <h3>Of course you need more, to go further</h3>
    <ul>
        <li><a href="https://utm.dizagn.com/documentation" target="_blank">The utm project documentation</a></li>
    </ul>
</div>